### ISSUE TITLE
Export to Eeschema

### ISSUE THREAD

**Issue by johnthagen** [xesscorp/skidl#68]
Would it be possible for `skidl` to export *into* Eeschema?

The use case, is that it would be really powerful to generate a circuit description in Python code using `skdl` and then visualize it in Eeschema.

**Comment by xesscorp** [comment]
I've done a small amount of work on generating schematics. Once you've got part placement and routing done, then generating a specific format like EESCHEMA wouldn't be hard. The hard part is generating an attractive placement and routing.

**Comment by johnthagen** [comment]
> The hard part is generating an attractive placement and routing.

Thanks for the response.

This was my thought as well. The thought I had was that if you were able to drop into the schematic directly from Python, either the Python side could try to do a small best-effort on the placement beforehand, or at least now that the data is in a schematic tool, the user has the option to do some manual edits to clean it up.

So the raw data could at least go directly Python -> Eeschema and the clean up could be deferred to the user?

**Comment by xesscorp** [comment]
Generating an EESCHEMA schematic would be relatively simple once a decent placement and routing were determined. Determining the placement and routing is the hard part. Giving a poorly-placed schematic in EESCHEMA is going to drive a user crazy. The components can be dragged into position, but straightening-out the wiring is a lot more difficult with the tools currently available.

The main purpose for the schematic is important. If it's just for verification that the SKiDL is doing what it should, then poor placement is not as important. If it's to generate a schematic to hand off to someone else, then it's a bigger problem.

**Comment by johnthagen** [comment]
> If it's to generate a schematic to hand off to someone else, then it's a bigger problem.

Yeah, that was the use case I was imagining. I was thinking that if the placement and routing wasn't great, the fact it was going into EESCHEMA (which couldn't be edited afterward) rather than a static PDF would still have value.

But I could very well be underestimating how painful it would be to manually clean up such a schematic manually.

**Comment by xesscorp** [comment]
Creating an EESCHEMA schematic, even a bad one, would be better than a PDF. At least it's editable. So that's a good idea. But editing it would still be extremely painful with the current EESCHEMA. I doubt anyone would want to do it twice.

**Comment by johnthagen** [comment]
@xesscorp I was thinking about this some more, and I think a middle ground solution could actually be really useful.

Instead of trying to auto-route wires, `skidl` could use net labels to represent all of the pin connections in a schematic.

Consider this image taken from an [online guide](https://kicad.txplore.com/index-p=153.html):

![image](https://user-images.githubusercontent.com/10340167/71309003-f7748600-23d0-11ea-8a98-707cdf7e232d.png)

Using net labels, I think the only API `skidl` would need to provide would be for each part:

- Which schematic page it belongs on
- It's x / y location in the schematic
- Possibly orientation (but this could default to the default for the schematic symbol)

I think this is an exciting idea for a couple reasons:

- It greatly reduces the complexity for `skidl`. Leave the layout/placement to the user, who can still use Python to describe the x/y schematic location
- The output is in an editable format, so if the user wants to touch it up after ward (adding wires, etc) they can, but they've got all the net information there to help them
- If the user outputs both Eeschema and Pcbnew output into a single project, I think highlight nets should work across Eeschema and Pcbnew, which would be pretty awesome.
- Using the KiCAD libraries, `skidl` should be able to use the schematic symbols already present and associated with footprints though a part, freeing the user from having to do all of those associated lookups.

**Comment by xesscorp** [comment]
This would be a way to start. I think that good part placement is of the most importance and this would be a way to start playing with that. Wiring would be relatively easy to route in after that.

You would need to know the bounding box of each part (to avoid overlaps) and the X/Y location of each pin (to know where to attach net labels). For KiCad parts, you'll find the base information in an attribute called `draw` from which you can calculate the bounding box and attachment points.

**Comment by johnthagen** [comment]
Blog about upcoming new Schematic format in KiCad 6: https://kicad-pcb.org/blog/2020/05/Development-Highlight-New-schematic-and-symbol-library-file-formats-are-now-the-default/

**Comment by falkartis** [comment]
I find this idea very interesting, my use case would probably be to visually check if what I'm writing is correct.
I have used in the past tools graphviz/dot to display dependency trees. It's open source project, I don't know if the licence allows to copy part of the positioning algorithm. It surely doesn't produce the best layout, but most of the times good enough to look at. I've used it to display quite large graphs (A3 paper).

**Comment by johnthagen** [comment]
What I think would be a really nice interface for `skidl` would be to leave the X/Y and routing up to the user and simply provide a convenient way to translate `skidl` Net components into Eeschematic positions.

This would allow `skidl` to not have to worry about complex automated positioning and allow users to use what ever algorithms they want to use.

**Comment by falkartis** [comment]
> This would allow skidl to not have to worry about complex automated positioning and allow users to use what ever algorithms they want to use.

Also a good idea, this way it can be kept simple, in this case it would be useful to somehow be able to access the geometry of the symbol, mostly bounding box, and relative pin positions and orientations.

**Comment by ryanm101** [comment]
I'd love this feature really useful for reverse engineering a pcb.. Though I had an idea that might be nicer as a starting point:

Use YAML (or JSON) to declare the connections and the devices something like below. Then have that generate your stub code or just use it to create the netlist. 
main.py
```
import yaml

class Component:
    def __init__(self, name, comp_type, pins=2, value=None):
        self.name = name
        self.type = comp_type
        self.value = value
        self.pin_count = pins
        self.pins = self.__initPins__()

    def __initPins__(self):
        pins = []
        i = 0
        while i < self.pin_count:
            pins.append(Pin(i))
            i += 1

        return tuple(pins)


class Pin:
    def __init__(self, name=None, pin_type=None):
        self.name = name
        self.type = pin_type
        self.connections = []

def populate_pcb(components_yml):
    hsh_comp = {}
    for comp in components_yml:
        k = next(iter(comp))
        i = 0
        count = 1 if "count" not in comp[k].keys() else comp[k]['count']
        pins = 2 if "pins" not in comp[k].keys() else comp[k]['pins']
        value = None if "value" not in comp[k].keys() else comp[k]['value']
        comp_type = None if "type" not in comp[k].keys() else comp[k]['type']
        # See if we already have a <letter> number and ensure we increment
        while k+str(i) in hsh_comp.keys():
            i += 1
        count = count + i

        while i < count:
            hsh_comp[k + str(i)] = Component(k + str(i), comp_type, pins, value)
            i += 1

    hsh_comp['GND'] = Component("GND", "POWER", 1, None)
    hsh_comp['VCC'] = Component("VCC", "POWER", 1, "5v")

    return hsh_comp


def populate_connections(components, connections):
    for conn in connections:
        k = next(iter(conn))
        if '[' in k:
            comp_name = k[0:k.index('[')]
            pin_num = int(k[k.index('[')+1:k.index(']')])
        else:
            comp_name = k
            pin_num = 0
        ((components[comp_name]).pins[pin_num]).connections += conn[k]


def main():
    with open(r"example.yaml") as f:
        pcb = yaml.load(f, Loader=yaml.FullLoader)
        f.close()

    print(pcb)
    components = populate_pcb(pcb["pcb"]["components"])
    populate_connections(components,pcb['pcb']['connections'])


if __name__ == "__main__":
    # execute only if run as a script
    main()
```
example.yml
```
pcb:
  components:
    - U:
        type: "16L8-25C"
        count: 5
        pins: 20
    - J:
        type: "spst"
        pins: 2
    - J:
        type: "dpst"
        pins: 4
    - D:
        type: "led"
        count: 2
    - D:
        type: "diode"
    - U:
        type: "unknown"
        pins: 14
    - M:
        type: "ZVP2106A"
        pins: 3
    - C:
        type: "capacitor"
        value: "10uf 63v"
    - C:
        type: "capacitor"
        value: "1uf 25v"
    - C:
        type: "capacitor"
        count: 4
    - R:
        type: "resistor"
        value: "1K"
        count: 6
    - R:
        type: "resistor"
        value: "4.7K"
    - R:
        type: "pot"
        value: "12.6K"
        pins: 3
    - U:
        type: "555Timer"
        pins: 8
    - J:
        type: "connector"
        pins: 86

  connections:
    - GND:
        - J2[1]
        - J2[2]
        - J2[3]
        - J2[4]
    - VCC:
        - J2[5]
    - C2[0]:
        - J2[2]
        - R0[0]
        - R1[0]
    - C2[1]:
        - J2[5]
    - R0[1]:
        - J2[54]
        - U0[8]
    - U0[4]:
        - U2[15]
```
